export const IMPORTCOL = 'IMPORTCOL'
export const FETCH_COLLECTION = 'FETCH_COLLECTION'
export const ADD_COLLECTION = 'ADD_COLLECTION'
export const ADD_COLLECTION_RESET = 'ADD_COLLECTION_RESET'
export const DELETE_COLLECTION = 'DELETE_COLLECTION'
export const DELETE_ALL_COLLECTIONS = "DELETE_ALL_COLLECTIONS"
export const EDIT_COLLECTION = 'EDIT_COLLECTION'
export const MOVE_COLLECTION = "MOVE_COLLECTION"
export const UPDATE_GEM_WITH_COLLECTION = "UPDATE_GEM_WITH_COLLECTION"
export const REMOVE_GEM_FROM_COLLECTION = "REMOVE_GEM_FROM_COLLECTION"
export const MOVE_GEMS = 'MOVE_GEMS'
export const UPDATE_BOOKMARK_EXISTING_COLLECTION = "UPDATE_GEM_EXISTING_COLLECITON"
export const RESET_COLLECTION_DATA = "RESET_COLLECTION_DATA"
export const ADD_IMPORTED_GEMS = "ADD_IMPORTED_GEMS"
export const SET_EXPANDED_KEYS = "SET_EXPANDED_KEYS"
export const MOVE_TO_ROOT = "MOVE_TO_ROOT"
export const UPLOAD_BOOKMARK_COVER = "UPLOAD_BOOKMARK_COVER"
export const UPLOAD_SCREENSHOTS = "UPLOAD_SCREENSHOTS"
export const GET_COLLECTION_BY_ID = "GET_COLLECTION_BY_ID"
export const GET_USER_COLLECTIONS = "GET_USER_COLLECTIONS"
export const SEARCH_DATA = "SEARCH_DATA"
export const SAVE_SELECTED_COLLECTION = "SAVE_SELECTED_COLLECTION"
export const UPLOAD_ICONS = "UPLOAD_ICONS"

export const UPDATE_COLLECTION = 'UPDATE_COLLECTION'
export const GET_SHARED_COLLECTIONS = "GET_SHARED_COLLECTIONS"
export const RESET_SHARED_COLLECTIONS = "RESET_SHARED_COLLECTIONS"
export const MOVE_GEM_TO_SHARED_COLLECTION = "MOVE_GEM_TO_SHARED_COLLECTION"
export const REMOVE_GEM_FROM_SHARED_COLLECTION = "REMOVE_GEM_FROM_SHARED_COLLECTION"
export const ADD_GEM_TO_SHARED_COLLECTION = "ADD_GEM_TO_SHARED_COLLECTION"
export const UPDATE_SHARED_COLLECTION = "UPDATE_SHARED_COLLECTION"
export const MOVE_SHARED_COLLECTION_TO_ROOT = "MOVE_SHARED_COLLECTION_TO_ROOT"
export const MOVE_COLLECTION_SHARED = "MOVE_COLLECTION_SHARED"

export const GET_SINGLE_COLLECTION = "GET_SINGLE_COLLECTION"
export const REMOVE_SHARED_COLLECTION = "REMOVE_SHARED_COLLECTION"
export const SHARE_COLLECTION_VIA_EMAIL = "SHARE_COLLECTION_VIA_EMAIL";
export const REMOVE_ACCESS_EMAIL = "REMOVE_ACCESS_EMAIL";
export const CHANGE_SECURITY_EMAIL = "CHANGE_SECURITY_EMAIL";

//link
export const SHARE_COLLECTION_VIA_LINK = "SHARE_COLLECTION_VIA_LINK";
export const CHECK_COLLECTION_VIA_LINK = "CHECK_COLLECTION_VIA_LINK";
export const REMOVE_ACCESS_LINK = "REMOVE_ACCESS_LINK";
export const CHANGE_SECURITY_LINK = "CHANGE_SECURITY_LINK";

//public
export const SHARE_COLLECTION_VIA_PUBLIC = "SHARE_COLLECTION_VIA_PUBLIC";
export const CHECK_COLLECTION_VIA_PUBLIC = "CHECK_COLLECTION_VIA_PUBLIC";
export const DISABLE_PUBLIC_LINK = "DISABLE_PUBLIC_LINK";
export const SET_PASSWORD_PUBLIC_LINK = "SET_PASSWORD_PUBLIC_LINK";

export const ADD_IMPORT_COLLECTION = "ADD_IMPORT_COLLECTION"
export const UPDATE_COLLECTION_DATA_FOR_IMPORT = "UPDATE_COLLECTION_DATA_FOR_IMPORT"
export const ADD_COLLECTION_ACTIVITY = "ADD_COLLECTION_ACTIVITY"

export const UPLOAD_UNSPLASH_IMAGE_IN_S3 = "UPLOAD_UNSPLASH_IMAGE_IN_S3"
export const GET_BOOKMARK_IN_COLLECTION = "GET_BOOKMARK_IN_COLLECTION"
export const SET_LOADED_KEYS = "SET_LOADED_KEYS"
export const ADD_COLLECTION_COUNT = "ADD_COLLECTION_COUNT"
export const GET_COLLECTION_BY_MEDIA_TYPE = "GET_COLLECTION_BY_MEDIA_TYPE"
export const GET_SAVED_TABS_COLLECTION = "GET_SAVED_TABS_COLLECTION"
export const GET_SAVED_TABS_GEMS = "GET_SAVED_TABS_GEMS"
export const GET_GEMS_ON_MEDIA_TYPES = "GET_GEMS_ON_MEDIA_TYPES"

export const CONFIG_LIMIT_FOR_COLLECTION = "CONFIG_LIMIT_FOR_COLLECTION"
export const CONFIG_COLLECTIONS = "CONFIG_COLLECTIONS"
export const UPLOAD_ALL_FILE_TYPE = "UPLOAD_ALL_FILE_TYPE"
export const GET_BOOKMARK_DETAILS_MICROLINK = "GET_BOOKMARK_DETAILS_MICROLINK"
export const FETCH_TECH_DOMAIN_DETAILS = "FETCH_TECH_DOMAIN_DETAILS"

export const GET_USER_SYNC_DATA = "GET_USER_SYNC_DATA"
export const UPDATE_COLLECTION_SEO_DETAILS = "UPDATE_COLLECTION_SEO_DETAILS"
export const UPDATE_GROUP_ACCESS = "UPDATE_GROUP_ACCESS"
export const SHARE_COLLECTION_VIA_EMAIL_GROUP = "SHARE_COLLECTION_VIA_EMAIL_GROUP"
export const UPLOAD_CSV_TEXT_LINKS = "UPLOAD_CSV_TEXT_LINKS";
export const GET_OPEN_AI_RESPONSE = "GET_OPEN_AI_RESPONSE";