export const FETCH_URL_DATA = 'FETCH_URL_DATA'
export const FETCH_URL_DATA_RESET = 'FETCH_URL_DATA_RESET'
export const FETCH_URL_SCREENSHOT = 'FETCH_URL_SCREENSHOT'
export const FETCH_URL_SCREENSHOT_RESET = 'FETCH_URL_SCREENSHOT_RESET'
export const FETCHING_SITE_DATA = "FETCHING_SITE_DATA"
export const SET_DATA_FROM_STORAGE = "SET_DATA_FROM_STORAGE"